### ISSUE TITLE
two issues on macos 10.12.3

### ISSUE THREAD

**Issue by guozheng** [pseudomuto/protoc-gen-doc#269]
Hi,

I used to be able to build successfully, but with the latest updates of macos, I started to have issues.

I am following the steps in [https://github.com/estan/protoc-gen-doc/blob/master/.travis.yml](https://github.com/estan/protoc-gen-doc/blob/master/.travis.yml )

first issue
=======
when I ran `qmake`, I got the SDK path error:
```
> qmake                                                                                                                                                               
Project ERROR: Could not resolve SDK Path for 'macosx'
```
After searched online, it is due to the `xcode-select` developer directory was changed with OS upgrade. BTW, make sure you have xcode and command line tools installed already. See details in [this post](http://stackoverflow.com/questions/17980759/xcode-select-active-developer-directory-error/17980786#17980786), simply running this command helped solve the issue:
```
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
```

second issue
==========
when I ran `make`, pdf doc is not generated, docbook, html and md files are good. It might be the fop command has 
```
> make                                                                                                                                               master [225664a] deleted untracked
protoc --doc_out=markdown,example.md:doc proto/*.proto
[libprotobuf WARNING google/protobuf/compiler/parser.cc:546] No syntax specified for the proto file: proto/Booking.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
[libprotobuf WARNING google/protobuf/compiler/parser.cc:546] No syntax specified for the proto file: proto/Customer.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
[libprotobuf WARNING google/protobuf/compiler/parser.cc:546] No syntax specified for the proto file: proto/Vehicle.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
protoc --doc_out=html,example.html:doc proto/*.proto
[libprotobuf WARNING google/protobuf/compiler/parser.cc:546] No syntax specified for the proto file: proto/Booking.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
[libprotobuf WARNING google/protobuf/compiler/parser.cc:546] No syntax specified for the proto file: proto/Customer.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
[libprotobuf WARNING google/protobuf/compiler/parser.cc:546] No syntax specified for the proto file: proto/Vehicle.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
protoc --doc_out=docbook,example.docbook:doc proto/*.proto
[libprotobuf WARNING google/protobuf/compiler/parser.cc:546] No syntax specified for the proto file: proto/Booking.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
[libprotobuf WARNING google/protobuf/compiler/parser.cc:546] No syntax specified for the proto file: proto/Customer.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
[libprotobuf WARNING google/protobuf/compiler/parser.cc:546] No syntax specified for the proto file: proto/Vehicle.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
fop -xml doc/example.docbook \
		-xsl /usr/share/xml/docbook/xsl-stylesheets-1.79.1/fo/docbook.xsl \
		-param use.extensions 0 \
		-param fop1.extensions 1 \
		-param paper.type A4 \
		-param page.orientation landscape \
		-pdf doc/example.pdf

USAGE
fop [options] [-fo|-xml] infile [-xsl file] [-awt|-pdf|-mif|-rtf|-tiff|-png|-pcl|-ps|-txt|-at [mime]|-print] <outfile>
 [OPTIONS]
  -version          print FOP version and exit
  -x                dump configuration settings
  -c cfg.xml        use additional configuration file cfg.xml
  -l lang           the language to use for user information
  -nocs             disable complex script features
  -r                relaxed/less strict validation (where available)
  -dpi xxx          target resolution in dots per inch (dpi) where xxx is a number
  -s                for area tree XML, down to block areas only
  -v                run in verbose mode (currently simply print FOP version and continue)

  -o [password]     PDF file will be encrypted with option owner password
  -u [password]     PDF file will be encrypted with option user password
  -noprint          PDF file will be encrypted without printing permission
  -nocopy           PDF file will be encrypted without copy content permission
  -noedit           PDF file will be encrypted without edit content permission
  -noannotations    PDF file will be encrypted without edit annotation permission
  -nofillinforms    PDF file will be encrypted without fill in interactive form fields permission
  -noaccesscontent  PDF file will be encrypted without extract text and graphics permission
  -noassembledoc    PDF file will be encrypted without assemble the document permission
  -noprinthq        PDF file will be encrypted without print high quality permission
  -a                enables accessibility features (Tagged PDF etc., default off)
  -pdfprofile prof  PDF file will be generated with the specified profile
                    (Examples for prof: PDF/A-1b or PDF/X-3:2003)

  -conserve         enable memory-conservation policy (trades memory-consumption for disk I/O)
                    (Note: currently only influences whether the area tree is serialized.)

  -cache            specifies a file/directory path location for the font cache file
  -flush            flushes the current font cache file

 [INPUT]
  infile            xsl:fo input file (the same as the next)
                    (use '-' for infile to pipe input from stdin)
  -fo  infile       xsl:fo input file
  -xml infile       xml input file, must be used together with -xsl
  -atin infile      area tree input file
  -ifin infile      intermediate format input file
  -imagein infile   image input file (piping through stdin not supported)
  -xsl stylesheet   xslt stylesheet

  -param name value <value> to use for parameter <name> in xslt stylesheet
                    (repeat '-param name value' for each parameter)

  -catalog          use catalog resolver for input XML and XSLT files
 [OUTPUT]
  outfile           input will be rendered as PDF into outfile
                    (use '-' for outfile to pipe output to stdout)
  -pdf outfile      input will be rendered as PDF (outfile req'd)
  -pdfa1b outfile   input will be rendered as PDF/A-1b compliant PDF
                    (outfile req'd, same as "-pdf outfile -pdfprofile PDF/A-1b")
  -awt              input will be displayed on screen
  -rtf outfile      input will be rendered as RTF (outfile req'd)
  -pcl outfile      input will be rendered as PCL (outfile req'd)
  -ps outfile       input will be rendered as PostScript (outfile req'd)
  -afp outfile      input will be rendered as AFP (outfile req'd)
  -tiff outfile     input will be rendered as TIFF (outfile req'd)
  -png outfile      input will be rendered as PNG (outfile req'd)
  -txt outfile      input will be rendered as plain text (outfile req'd)
  -at [mime] out    representation of area tree as XML (outfile req'd)
                    specify optional mime output to allow the AT to be converted
                    to final format later
  -if [mime] out    representation of document in intermediate format XML (outfile req'd)
                    specify optional mime output to allow the IF to be converted
                    to final format later
  -print            input file will be rendered and sent to the printer
                    see options with "-print help"
  -out mime outfile input will be rendered using the given MIME type
                    (outfile req'd) Example: "-out application/pdf D:\out.pdf"
                    (Tip: "-out list" prints the list of supported MIME types and exits)
  -svg outfile      input will be rendered as an SVG slides file (outfile req'd)
                    Experimental feature - requires additional fop-sandbox.jar.

  -foout outfile    input will only be XSL transformed. The intermediate
                    XSL-FO file is saved and no rendering is performed.
                    (Only available if you use -xml and -xsl parameters)


 [Examples]
  fop foo.fo foo.pdf
  fop -fo foo.fo -pdf foo.pdf (does the same as the previous line)
  fop -xml foo.xml -xsl foo.xsl -pdf foo.pdf
  fop -xml foo.xml -xsl foo.xsl -foout foo.fo
  fop -xml - -xsl foo.xsl -pdf -
  fop foo.fo -mif foo.mif
  fop foo.fo -rtf foo.rtf
  fop foo.fo -print
  fop foo.fo -awt

Feb 25, 2017 11:19:42 AM org.apache.fop.cli.Main startFOP
SEVERE: Exception
java.io.FileNotFoundException: Error: xsl file /usr/share/xml/docbook/xsl-stylesheets-1.79.1/fo/docbook.xsl not found
	at org.apache.fop.cli.CommandLineOptions.checkSettings(CommandLineOptions.java:952)
	at org.apache.fop.cli.CommandLineOptions.parse(CommandLineOptions.java:172)
	at org.apache.fop.cli.Main.startFOP(Main.java:169)
	at org.apache.fop.cli.Main.main(Main.java:217)

make: *** [doc/example.pdf] Error 1
```
environment that I am using:
```
protobuf 3.2.0
fop 2.1
```
It seems that the `docbook.xml` file is not found or the path is not correctly configured on macos. There are several docbook.xsl files in docbook-xsl package installed by homebrew, but I am not sure which one is the correct one to use, maybe you can fix this path issue and fop will generate pdf correctly?
```
/usr/local/Cellar/docbook-xsl/1.79.1/docbook-xsl/epub/docbook.xsl
/usr/local/Cellar/docbook-xsl/1.79.1/docbook-xsl/epub3/docbook.xsl
/usr/local/Cellar/docbook-xsl/1.79.1/docbook-xsl/epub3/profile-docbook.xsl
/usr/local/Cellar/docbook-xsl/1.79.1/docbook-xsl/fo/docbook.xsl
/usr/local/Cellar/docbook-xsl/1.79.1/docbook-xsl/fo/profile-docbook.xsl
/usr/local/Cellar/docbook-xsl/1.79.1/docbook-xsl/html/docbook.xsl
/usr/local/Cellar/docbook-xsl/1.79.1/docbook-xsl/html/profile-docbook.xsl
/usr/local/Cellar/docbook-xsl/1.79.1/docbook-xsl/manpages/docbook.xsl
/usr/local/Cellar/docbook-xsl/1.79.1/docbook-xsl/manpages/profile-docbook.xsl
/usr/local/Cellar/docbook-xsl/1.79.1/docbook-xsl/xhtml/docbook.xsl
/usr/local/Cellar/docbook-xsl/1.79.1/docbook-xsl/xhtml/profile-docbook.xsl
/usr/local/Cellar/docbook-xsl/1.79.1/docbook-xsl/xhtml-1_1/docbook.xsl
/usr/local/Cellar/docbook-xsl/1.79.1/docbook-xsl/xhtml-1_1/profile-docbook.xsl
/usr/local/Cellar/docbook-xsl/1.79.1/docbook-xsl/xhtml5/docbook.xsl
/usr/local/Cellar/docbook-xsl/1.79.1/docbook-xsl/xhtml5/profile-docbook.xsl
/usr/local/Cellar/docbook-xsl/1.79.1/docbook-xsl/xhtml5/xhtml-docbook.xsl
/usr/local/Cellar/docbook-xsl/1.79.1/docbook-xsl/xhtml5/xhtml-profile-docbook.xsl
/usr/local/Cellar/docbook-xsl/1.79.1/docbook-xsl-ns/epub/docbook.xsl
/usr/local/Cellar/docbook-xsl/1.79.1/docbook-xsl-ns/epub3/docbook.xsl
/usr/local/Cellar/docbook-xsl/1.79.1/docbook-xsl-ns/epub3/profile-docbook.xsl
/usr/local/Cellar/docbook-xsl/1.79.1/docbook-xsl-ns/fo/docbook.xsl
/usr/local/Cellar/docbook-xsl/1.79.1/docbook-xsl-ns/fo/profile-docbook.xsl
/usr/local/Cellar/docbook-xsl/1.79.1/docbook-xsl-ns/html/docbook.xsl
/usr/local/Cellar/docbook-xsl/1.79.1/docbook-xsl-ns/html/profile-docbook.xsl
/usr/local/Cellar/docbook-xsl/1.79.1/docbook-xsl-ns/manpages/docbook.xsl
/usr/local/Cellar/docbook-xsl/1.79.1/docbook-xsl-ns/manpages/profile-docbook.xsl
find: docbook: No such file or directory
/usr/local/Cellar/docbook-xsl/1.79.1/docbook-xsl-ns/xhtml/docbook.xsl
/usr/local/Cellar/docbook-xsl/1.79.1/docbook-xsl-ns/xhtml/profile-docbook.xsl
/usr/local/Cellar/docbook-xsl/1.79.1/docbook-xsl-ns/xhtml-1_1/docbook.xsl
/usr/local/Cellar/docbook-xsl/1.79.1/docbook-xsl-ns/xhtml-1_1/profile-docbook.xsl
/usr/local/Cellar/docbook-xsl/1.79.1/docbook-xsl-ns/xhtml5/docbook.xsl
/usr/local/Cellar/docbook-xsl/1.79.1/docbook-xsl-ns/xhtml5/profile-docbook.xsl
/usr/local/Cellar/docbook-xsl/1.79.1/docbook-xsl-ns/xhtml5/xhtml-docbook.xsl
/usr/local/Cellar/docbook-xsl/1.79.1/docbook-xsl-ns/xhtml5/xhtml-profile-docbook.xsl
```

**Comment by guozheng** [comment]
another possible fix is to add `'syntax = "proto2";' or 'syntax = "proto3";`, seems like protoc starts to give warnings now.

**Comment by guozheng** [comment]
I think I found the path for the docbook.xsl installed through homebrew on mac: `/usr/local/Cellar/docbook-xsl/1.79.1/docbook-xsl-ns/fo/docbook.xsl`, updated the Makefile and will try to send a PR soon...

**Comment by sumancholleti** [comment]
Hello 

Can any one get me the steps to generate html from Proto file in mac

**Comment by guozheng** [comment]
@sumancholleti you can follow instructions for set this up in macOS here: https://github.com/guozheng/protoc-gen-doc/blob/e0cfaac84c95b3fe01c687fba06c1de9af496d6a/BUILDING.md

then follow the README.md to generate the html:
https://github.com/estan/protoc-gen-doc/blob/master/README.md

**Comment by sumancholleti** [comment]
okay thanks Estan helped me

**Comment by estan** [comment]
Please see my recent addition to the README.md, copied below. My sincerest apologies for this.

```
To all users of `protoc-gen-doc`: This project is now unmaintained and
seeking a new maintainer. The reason for this is two-fold:

1. I'm not using Protocol Buffers myself anymore, and haven't done so
   for years.

2. I'm too busy with work and other projects to keep developing
   the tool, deal with feature requests and PRs.

Too all those who have outstanding pull requests and/or issues filed:
I'm really sorry, and thank you so much for your contributions, but I
simply don't have time for the project anymore, even if it is quite
low-maintenance.

Are you a user of `protoc-gen-doc` who feel you could take over? Great!
Please get in touch with me privately and we can discuss how to best
proceed (GitHub forking and transferring of Travis CI / AppVeyor / Open
Build Service accounts). The code is quite simple and only moderate C++
skills and some familiarity with Qt is needed.

Again, to all users: I'm sorry for this inconvenience, but it would be
dishonest of me to continue claiming maintainership of this project
when I don't have the time anymore.
```

**Comment by pseudomuto** [comment]
Closing since this project has been ported to go
